name: Django BlogNest Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: core_db
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Compose
      run: docker compose up -d --build
    - name: Wait for DB
      run: docker compose run --rm backend pytest
    - name: Run Tests
      run: docker compose exec backend sh -c "pytest ."
